### ISSUE TITLE
about micrometer

### ISSUE THREAD

**Issue by HelloTo4x** [pjfanning/zio-metrics-micrometer#5]
Hi, i am reading your project, why do you use Micrometer for collecting metric ? why don't you use Grafana + Prometheus to collect log and metric ? Do you know about pros and cons of Micrometer, can you tell me about it

**Comment by pjfanning** [comment]
Please read https://micrometer.io/ - in short, Micrometer is an API that lets you generate metrics in many formats including Prometheus. Changing from one format to another does not involve rewriting all your metrics code.
